import { PROJECT_STEPS } from "../../../constants/common";

export const VALIDATION_FIELDS = [
  {
    id: 1,
    field: "summary",
    translation: "validation.summary",
    validation: ["required"],
    phases: [1, 2],
    step: PROJECT_STEPS.SUMMARY,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 2,
    field: "revenue_source",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.revenue_source",
    step: PROJECT_STEPS.SUMMARY,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 3,
    field: "proposed_funding_source",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.proposed_funding_source",
    step: PROJECT_STEPS.SUMMARY,
    app: ["jm"],
    resource: "project",
  },

  {
    id: 4,
    field: "start_date",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.start_date",
    step: PROJECT_STEPS.SUMMARY,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 5,
    field: "end_date",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.end_date",
    step: PROJECT_STEPS.SUMMARY,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 6,
    field: "locations",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.location",
    step: PROJECT_STEPS.SUMMARY,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 7,
    field: "project_goal",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.goal",
    step: PROJECT_STEPS.SUMMARY,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 8,
    field: "procurement_modality",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.procurement_modality",
    step: PROJECT_STEPS.SUMMARY,
    app: ["jm"],
    resource: "project",
  },

  {
    id: 9,
    field: "governance",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.governance",
    step: PROJECT_STEPS.PROJECT_BACKGROUND,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 10,
    field: "me_strategies",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.me_strategies",
    step: PROJECT_STEPS.PROJECT_BACKGROUND,
    app: ["jm"],
    resource: "project",
  },

  {
    id: 11,
    field: "problem_statement",
    translation: "validation.problem_statement",
    validation: ["required"],
    phases: [1, 2],
    step: PROJECT_STEPS.PROJECT_BACKGROUND,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 12,
    field: "problem_cause",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.problem_cause",
    step: PROJECT_STEPS.PROJECT_BACKGROUND,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 13,
    field: "problem_effects",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.problem_effects",
    step: PROJECT_STEPS.PROJECT_BACKGROUND,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 14,
    field: "justification",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.justification",
    step: PROJECT_STEPS.PROJECT_BACKGROUND,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 15,
    field: "stakeholder_consultation",
    validation: ["required"],
    phases: [1],
    translation: "validation.stakeholders",
    step: PROJECT_STEPS.PROJECT_BACKGROUND,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 16,
    field: "stakeholders",
    validation: ["required"],
    innerFields: [
      { name: true },
      { description: true },
      { interest_level: true },
      { influence_level: true },
      { communication_channel: true },
      { engagement_frequency: true },
      { responsible_entity: true },
    ],
    phases: [2],
    translation: "validation.stakeholders",
    step: PROJECT_STEPS.STAKEHOLDERS,
    app: ["jm"],
    resource: "project",
  },

  {
    id: 17,
    field: "goal",
    validation: ["required"],
    phases: [2],
    translation: "validation.goal",
    step: PROJECT_STEPS.RESULT_MATRIX,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 18,
    field: "indicators",
    innerFields: [
      { name: true },
      { baseline: true },
      { verification_means: true },
    ],
    validation: ["required"],
    phases: [2],
    translation: "validation.goal_indicators",
    step: PROJECT_STEPS.RESULT_MATRIX,
    app: ["jm"],
  },
  {
    id: 19,
    field: "outcomes",
    innerFields: [{ name: true }],
    validation: ["required"],
    phases: [2],
    translation: "validation.outcomes",
    step: PROJECT_STEPS.RESULT_MATRIX,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 20,
    field: "outcomes.indicators",
    validation: ["required"],
    innerFields: [
      { name: true },
      { baseline: true },
      { verification_means: true },
      { assumptions: true },
      { risk_factors: true },
    ],
    phases: [2],
    translation: "validation.outcomes_indicators",
    step: PROJECT_STEPS.RESULT_MATRIX,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 21,
    field: "outputs",
    validation: ["required"],
    innerFields: [
      { name: true },
      { outcome_ids: true },
      { organization_ids: true },
      { component_id: true },
      { description: true },
    ],
    phases: [2],
    translation: "validation.outputs",
    step: PROJECT_STEPS.RESULT_MATRIX,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 22,
    field: "outputs.indicators",
    validation: ["required"],
    innerFields: [
      { name: true },
      { baseline: true },
      { verification_means: true },
      { assumptions: true },
      { risk_factors: true },
    ],
    phases: [2],
    translation: "validation.outputs_indicators",
    step: PROJECT_STEPS.RESULT_MATRIX,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 23,
    field: "baseline",
    validation: ["required"],
    phases: [2],
    translation: "validation.baseline",
    step: PROJECT_STEPS.RESULT_MATRIX,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 24,
    field: "components",
    innerFields: [{ name: true }, { description: true }],
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.components",
    step: PROJECT_STEPS.COST_ESTIMATES,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 25,
    field: "components.investments",
    validation: ["required"],
    innerFields: [{ fund_id: true }],
    phases: [2],
    translation: "validation.components_investments",
    step: PROJECT_STEPS.COST_ESTIMATES,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 26,
    field: "components.subcomponents",
    innerFields: [{ name: true }, { description: true }],
    validation: ["required"],
    phases: [2],
    translation: "validation.components_subcomponents",
    step: PROJECT_STEPS.COST_ESTIMATES,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 27,
    field: "om_costs",
    innerFields: [{ fund_id: true }, { costing_id: true }],
    validation: ["required"],
    phases: [2],
    translation: "validation.om_costs",
    step: PROJECT_STEPS.OM_COSTS,
    app: ["jm"],
    resource: "project",
  },

  {
    id: 28,
    field: "ppp_similar_reference",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.ppp_similar_reference",
    step: PROJECT_STEPS.PROCUREMENT,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 29,
    field: "ppp_interest",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.ppp_interest",
    step: PROJECT_STEPS.PROCUREMENT,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 30,
    field: "ppp_impediments",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.ppp_impediments",
    step: PROJECT_STEPS.PROCUREMENT,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 31,
    field: "ppp_risk_allocation",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.ppp_risk_allocation",
    step: PROJECT_STEPS.PROCUREMENT,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 32,
    field: "ndp_strategies",
    validation: ["required"],
    phases: [1, 2],
    innerFields: [
      { ndp_goal_id: true },
      { ndp_outcome_id: true },
      { ndp_sdgs_ids: true },
      { ndp_strategy_ids: true },
    ], //TODO validate one of "ndp_strategy_id", "ndp_sdg_id"
    translation: "validation.ndp_strategy_id",
    step: PROJECT_STEPS.NDP,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 33,
    field: "ndp_policy_alignment",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.ndp_policy_alignment",
    step: PROJECT_STEPS.NDP,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 34,
    field: "ndp_compliance",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.ndp_compliance",
    step: PROJECT_STEPS.NDP,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 35,
    field: "default_option_name",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.default_option_name",
    step: PROJECT_STEPS.OPTIONS_ANALYSIS,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 36,
    field: "default_option_description",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.default_option_description",
    step: PROJECT_STEPS.OPTIONS_ANALYSIS,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 37,
    field: "default_option_description_impact",
    validation: ["required"],
    phases: [1, 2],
    translation: "validation.default_option_description_impact",
    step: PROJECT_STEPS.OPTIONS_ANALYSIS,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 38,
    field: "project_options",
    validation: ["required"],
    phases: [1],
    innerFields: [
      { name: true },
      { description: true },
      { swot_analysis: true },
      { start_date: true },
      { end_date: true },
      { capital_expenditure: true },
      { funding_modality: true },
    ],
    translation: "validation.project_options",
    step: PROJECT_STEPS.OPTIONS_ANALYSIS,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 39,
    field: "project_options",
    validation: ["required"],
    phases: [2],
    innerFields: [
      { name: true },
      { description: true },
      { swot_analysis: true },
      { start_date: true },
      { end_date: true },
      { capital_expenditure: true },
      { funding_modality: true },
      { financial_evaluation: true },
      { economic_evaluation: true },
      { stakeholder_evaluations: true },
    ],
    translation: "validation.project_options",
    step: PROJECT_STEPS.OPTIONS_ANALYSIS,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 41,
    field: "climate_risks",
    validation: ["required"],
    phases: [2],
    innerFields: [
      { climate_hazard: true },
      { exposure_risk: true },
      { vulnerability_risk: true },
      { overall_risk: true },
      { vulnerability_impact: true },
    ],
    translation: "validation.climate_risks",
    step: PROJECT_STEPS.CLIMATE_RISK_ASSESSMENT,
    app: ["jm"],
    resource: "project",
  },
  {
    id: 42,
    field: "project_risks",
    validation: ["required"],
    phases: [2],
    innerFields: [
      { name: true },
      { impact_level: true },
      { probability: true },
      { score: true },
      { response: true },
      { owner: true },
    ],
    translation: "validation.project_risks",
    step: PROJECT_STEPS.RISK_ASSESSMENT,
    app: ["jm"],
    resource: "project",
  },
];
